openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/open'
paths:
  /forget-password:
    post:
      summary: Forget Password
      description: Forget Password
      operationId: forgetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Email
                  example: user@example.com
                new_password:
                  type: string
                  format: password
                  description: New Password
                  example: newpassword123
                ver_code:
                  type: string
                  description: Verification Code
                  example: ABCDE
      responses:
        '200':
          description: Reset Password Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Reset Password Success
        '400':
          description: Request Error or Not Registered or Password Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Request Error
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
