openapi: 3.0.0
info:
  title: Ganxue Server API
  description: Ganxue Server API for user reset-password functionality.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/auth'
paths:
  /reset-password:
    post:
      summary: 用户重置密码
      description: 用户通过邮箱和旧密码或验证码重置密码。
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: 用户邮箱地址。
                  example: user@example.com
                old_password:
                  type: string
                  format: password
                  description: 用户旧密码。
                  example: oldpassword123
                new_password:
                  type: string
                  format: password
                  description: 用户新密码。
                  example: newpassword123
      responses:
        '200':
          description: 重置密码成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 重置密码成功
        '400':
          description: 请求错误或未注册或密码错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 请求错误
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 服务器错误
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
